name: 'dbt_transform'
version: '1.0.0'
config-version: 2
profile: 'dbt_transform'
model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
models:
  dbt_transform:
    +materialized: table
    +schema: dbt_transform
    +enabled: true
seeds:
  dbt_transform:
    +schema: dbt_transform
    +enabled: true